Repository Challengers-BOD/front, pull requests merged in 2024-08, with the labels that each got.

#34 #24feature/challenge details/users
  src/App.vue
  src/components/ChallengeContent.vue
  src/components/ChallengeList.vue
  src/components/ChallengeMyPage.vue
  src/components/ChallengeSideBar.vue
  src/components/VerificationFrom.vue
  src/router/index.js
  src/views/Home.vue
  src/views/MyPage.vue
Labels: feat, fix

#35 #3feature/admins
  src/components/CreateChallengeModal.vue
  src/components/EditChallengeModal.vue
  src/router/index.js
  src/views/Admin.vue
  src/views/AdminChallengeDetail.vue
  src/views/AdminUsers.vue
Labels: feat

#37 #36fix/getchallenges 페이지처리 수정
  src/components/ChallengeContent.vue
  src/components/ChallengeList.vue
Labels: fix

#40 feat / 헤더에 관리자 페이지 연결 추가
  src/components/Header.vue
Labels: feat

#42 update : 챌린지 인증 상태 목록 조회 ui
  src/components/ChallengeSideBar.vue
  src/components/VerificationFrom.vue
  src/components/VerificationList.vue
  src/router/index.js
  src/views/MyPage.vue
Labels: feat

#46 fix : 절대경로 수정
  src/axios.js
  src/components/ChallengeCard.vue
  src/components/ChallengeContent.vue
  src/components/ChallengeList.vue
  src/components/myPage/VerificationModal.vue
  src/main.js
  src/store/index.js
  src/views/SignUp.vue
  vue.config.js
Labels: fix

#59 update : mainPage - 포인트 랭킹 조회
  src/components/HeroSection.vue
  src/components/PointRankingSection.vue
  src/views/Home.vue
  yarn.lock
Labels: feat

#70 #69fix/get category of challenge
  src/components/ChallengeList.vue
Labels: fix

#72 refactor / 어드민 챌린지 수 카운트 백엔드 api 연결
  src/views/Admin.vue
Labels: refactor

#74 #73 어드민 유저 카운트 기능 구현
  src/views/AdminUsers.vue
Labels: refactor

#76 #75 refactor / 챌린지 참가인원 및 인원제한 프론트 표시
  src/components/ChallengeCard.vue
  src/components/ChallengeContent.vue
  src/components/ChallengeList.vue
Labels: refactor

#78 #77fix/image logo 및 문구 수정
  src/components/ChallengeContent.vue
  src/components/Footer.vue
  src/components/LoginModal.vue
  src/views/Admin.vue
  src/views/AdminChallengeDetail.vue
  src/views/AdminUsers.vue
  src/views/SignUp.vue
Labels: fix

#80 #79fix/get point ranking list
  src/components/ChallengeContent.vue
  src/components/ChallengeVerification.vue
  src/components/PointRankingSection.vue
Labels: fix

#87 bug, fix : 마이페이지-인증하기 버튼 오류 수정
  src/components/myPage/VerificationModal.vue
  src/views/myPage/MyPage.vue
Labels: fix

#93 #92feature/challenges/search
  src/components/ChallengeList.vue
Labels: feat

#94 챌린지 검색기능 구현
  src/App.vue
  src/components/ChallengeList.vue
Labels: feat
