Repository Challengers-BOD/front, pull requests merged in 2024-07, with the labels that each got.

#6 #5feature/mainpage 챌린지 전체조회
  src/App.vue
  src/assets/styles.css
  src/axios.js
  src/components/ChallengeCard.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/HeroSection.vue
  src/main.js
  src/router/index.js
  src/views/Home.vue
  vue.config.js
  yarn.lock
Labels: feat

#9 #8feature/challengedetails
  package-lock.json
  package.json
  src/components/ChallengeCard.vue
  src/components/ChallengeContent.vue
  src/components/ChallengeSidebar.vue
  src/components/ChallengeVerification.vue
  src/router/index.js
  yarn.lock
Labels: feat

#13 #12fix/mainpage 챌린지 전체조회 -> top10 조회
  src/components/ChallengeCard.vue
  src/components/ChallengeContent.vue
  src/components/ChallengeVerification.vue
  src/components/Header.vue
Labels: fix

#15 #14feature/getchallenges
  package-lock.json
  src/components/ChallengeList.vue
  src/components/Header.vue
  src/router/index.js
Labels: feat

#22 #3feature/admins
  src/components/EditChallengeModal.vue
  src/views/Admin.vue
Labels: feat

#23 #20feature/challenge verification
  src/components/ChallengeCard.vue
  src/components/ChallengeList.vue
  src/components/VerificationFrom.vue
  src/router/index.js
Labels: feat, fix

#25 #24feature/challenge details/users
  src/components/ChallengeContent.vue
Labels: feat

#27 update : 챌린지 신청하기 구현
  src/components/ChallengeContent.vue
  src/store/index.js
Labels: feat

#28 #3feature/admins
  src/router/index.js
  src/views/Admin.vue
  src/views/AdminChallengeDetail.vue
Labels: feat

#29 #24feature/challenge details/users
  src/components/ChallengeContent.vue
  src/components/ChallengeSidebar.vue
Labels: feat

#30 feat / 관리자 챌린지 인증 요청 목록 조회 및 승인 거절 기능 구현
  src/views/AdminChallengeDetail.vue
Labels: feat
